### ISSUE TITLE
Merge Shop Costs

### ISSUE THREAD

**Issue by DragoNext** [DragoNext/AqwDoIhave#7]
1. Calculate cost of all merge shop excluding owned items.
2. Display it to user.
Display Position ideas:
<details>
<summary>On Right Side of Merge Shop</summary>

![image](https://user-images.githubusercontent.com/49029552/204101645-ad35fa88-3023-4e20-9031-1597cc9ee546.png)

</details>
<details>
<summary>On Bottom of Merge Shop</summary>

![image](https://user-images.githubusercontent.com/49029552/204101696-1f964769-1570-4414-a765-c4a32a35b6a0.png)

</details>
Display will contain:

List of items needed like that:

MergeShop Name:   X/20 items 
* (MonsterDrop Icon) Item 1 x100 
* (QuestDrop Icon) Item 2 x200
* (MergeShop Icon) Item 3 x300 

(Need to remember)
Non items eg. Vouchers. from being needed to Complete Merge shop 
When Merge Shop Completed (Highlight it on green on http://aqwwiki.wikidot.com/merge-shops and highlight Title)

**Comment by Quannh1511** [comment]
On Right Side of Merge Shop is the most recognizable

**Comment by DragoNext** [comment]
{In progress}
![image](https://user-images.githubusercontent.com/49029552/205466143-aac3d365-b2e8-41ad-a5de-69437a7320aa.png)
Currently have that in progress, i would like to have feedback, the thing is i'm not sure about naming scheme of the table.
Also still have not recursive item check.

**Comment by Quannh1511** [comment]
As far as I see it currently, the columns in the table represent all the required resources. I think that makes sense, too, because it helps with clarity. For the time being, I think that's fine, you need to rearrange the resources with a small amount, so you should put them first. And when enough, you can change the color or a status bar something, must be easy to recognize.

**Comment by Quannh1511** [comment]
I have questions. Under what conditions are you calculating these items. Is it all or just non-existent items.

**Comment by Quannh1511** [comment]
These 2 columns you should balance with below to make the interface look better.
![image](https://user-images.githubusercontent.com/107485615/205470511-cb19c461-672c-49cf-8654-63700c575138.png)

**Comment by DragoNext** [comment]
![image](https://user-images.githubusercontent.com/49029552/206643154-cf5c6dc5-e86f-43b0-81a4-fbabd602409f.png)
Currently have that, still working on:
1. Only Ac Items Filter 
2. ProgressBar (It will be between 2 tables on right) 
3. When item is acquired hide it or move to the bottom of table (To make it clearer to read) 

And about your question:
> I have questions. Under what conditions are you calculating these items. Is it all or just non-existent items.
Just non existent items, i don't think there is need to include already acquired items.
Also all resource items under "Item Needed" row have link to wiki page of item - I think about changing it to the monster/quest from which it is acquired.

**Comment by Quannh1511** [comment]
With the demo image, I feel very good, but need to have a test first, then I have an accurate opinion.

**Comment by Quannh1511** [comment]
Resources when qualified, put it to the bottom row (should be).

**Comment by Quannh1511** [comment]
Displaying the selling price of the resource is also a good idea, but I think users will go to the link to search rather than look at the suggested image because very few people know the icon you create.

**Comment by Quannh1511** [comment]
It looks like you're testing in a dark interface, so this part is hard to see.
![image](https://user-images.githubusercontent.com/107485615/206867076-1c6571c3-801d-4bbe-8470-3a221713f2c9.png)

**Comment by Quannh1511** [comment]
I find it unbalanced, it should be in the middle.
![image](https://user-images.githubusercontent.com/107485615/206867186-c8c04c11-985a-43c6-ab43-74e1a497a40b.png)

**Comment by Quannh1511** [comment]
What is this part, I don't understand its effect yet.
![image](https://user-images.githubusercontent.com/107485615/206867503-f1c48e04-3427-47f8-8f83-1e9c98f9914a.png)

**Comment by DragoNext** [comment]
It's percentage of items, Acquired / In Merge shop

**Comment by Quannh1511** [comment]
Looks like this is a select and save option in the browser, why not on tabs. Because it will crash when the user accesses the tab again. I think it should be the default button, and it should be refreshed, not saved.
In addition, I find its interface quite blurry, users will not notice. If it was close to the title, it would probably be better.
![image](https://user-images.githubusercontent.com/107485615/206867597-fb21283e-2e19-4a44-8236-bca73fbc1302.png)

**Comment by Quannh1511** [comment]
Is bug.
![image](https://user-images.githubusercontent.com/107485615/206868901-e4260a95-8ae9-45eb-9f0a-6706ac5a8f3c.png)

**Comment by Quannh1511** [comment]
1. http://aqwwiki.wikidot.com/search-items-by-tag/parent/Merge%20Shops/tags/-_index%20-_redirect/perPage/50/order/title
2. http://aqwwiki.wikidot.com/search-items-by-tag/parent/-=/tags/-_index%20-_redirect/perPage/50/order/title

These are 2 websites that have an error rate because they contain the keyword 'merge shop'. You should exclude these 2 sites.

![image](https://user-images.githubusercontent.com/107485615/208095934-b56a8a58-f3f8-4edc-9671-9b82ad39986e.png)

**Comment by DragoNext** [comment]
Fixed that with that added general exclusion of "/search-items-by-tag" so there shouldn't be any other false positives. 8d9c91a0e66f32cf2a022d4064aee49a62b96bc0

**Comment by Quannh1511** [comment]
Hello, I'm back. About this time I have a suggestion.
Here it still shows the same calculated items, but it will have an additional item showing the total resource notes of the legends items.
![image](https://user-images.githubusercontent.com/107485615/212479883-54c6a418-4056-4232-b767-e8007c657019.png)

**Comment by DragoNext** [comment]
I don't understand what exactly you mean, if you mean exclusion and inclusion of legend items, i'm currently working on the filtering, and making calculation update on change of these filters, it's been more slower as i also started making item scraper for wiki, and other stuff.

Example of filters: (I think it's the best position for them currently)
![image](https://user-images.githubusercontent.com/49029552/212669399-4df680c5-a435-4821-820f-e6da7baf9ec1.png)

Item Scrapper results (^o^)
![image](https://user-images.githubusercontent.com/49029552/212670085-a8f0a3dc-91ab-4548-b50b-e2f3c4e268b7.png)

I hope the filters and calculation will be done before next week.

**Comment by Quannh1511** [comment]
I mean it will be necessary to show the total of the legend item's resources separately from the total of the calculated items.

Here is the example shown:
- Legend: 10 resources
- Toal (Ac, legend, gold): 100 resources

**Comment by Quannh1511** [comment]
Filter calculation is also needed.

**Comment by Quannh1511** [comment]
Does your filter work when user selects AC - Legend It will search only by those 2 keywords or get all Legends.

**Comment by Quannh1511** [comment]
Because I think, just having the Legend tag will get everything related to it.

**Comment by Quannh1511** [comment]
It will have many options like:
- Ac
- Legend
- Seasonal
- Special

I want Legend related items to be counted in the filter.

**Comment by DragoNext** [comment]
> Does your filter work when user selects AC - Legend It will search only by those 2 keywords or get all Legends.

Yes it does it will only narrow search by those 2 tags.

Ac + Normal = Only Ac items without other tags.
Ac = All Ac Items.
Legend + Normal = Only Non Ac Legend items without other tags.
Legend = All Legend items 
Normal = Shows only items without tags.
All selected / All not selected = All items shown.

Currently it works like that, as it makes the most sense i think.

Also i don't think adding seasonal filtering or special is necessary, as if merge shop is seasonal all items in it are seasonal same for special.

**Comment by Quannh1511** [comment]
For now, just do what you think is appropriate, I will comment later. And I think you're on the right track.
